[package]
name = "normalize-derive"
version = "0.1.0"
edition = "2024"
description = "Normalize"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
