[package]
name = "normalize-openapi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OpenAPI client code generation"

[dependencies]
serde_json.workspace = true
